project: 
  type: website

website:
  title: "Centenario Rent a Car"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/your_url
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Centenario"


  navbar:
    background: primary
    search: true   
    right:
      - text: "Viajes de Traslado"
        file: index.qmd

      

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



